"""cities title_with_preposition

Revision ID: 2a80b10f4fe5
Revises: cb946ef457f2
Create Date: 2020-06-17 13:32:58.867593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a80b10f4fe5'
down_revision = 'cb946ef457f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('title_with_preposition', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###
    # ### commands added by Igor
    op.execute("INSERT INTO cities(title, title_with_preposition, country, region) "
               "VALUES('Пенза', 'в Пензе', 'RU', 'Пензенская область')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'title_with_preposition')
    # ### end Alembic commands ###
